--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "e:\12\TestCase\test_request.py", line 66, in <module>
    pytest.main(["--alluredir", report_path])
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 120, in runtestprotocol
    rep = call_and_report(item, "setup", log)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 311, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 150, in pytest_runtest_setup
    item.session._setupstate.prepare(item)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 449, in prepare
    col.setup()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 1647, in setup
    self._request._fillfixtures()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 568, in _fillfixtures
    item.funcargs[argname] = self.getfixturevalue(argname)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 581, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 601, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 687, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 1072, in execute
    result = hook.pytest_fixture_setup(fixturedef=self, request=request)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 1126, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 925, in call_fixture_func
    fixture_result = next(generator)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 811, in xunit_setup_class_fixture
    _call_with_optional_argument(func, self.obj)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 739, in _call_with_optional_argument
    func(arg)
  File "E:\12\TestCase\test_request.py", line 36, in setup_class
    requestdata=RequestsHandler().post_Req(url=url,data="",json=json,headers="",params="")
  File ".\Common\requestbase.py", line 33, in post_Req
    self.logger.info(f'连通接口"{url}",接口data为:"{data}",接口json{json}')
Message: '连通接口"https://gateway-stg.jmj1995.com/authority/auth/login",接口data为:"",接口json{\'groupId\': \'3\', \'username\': \'zaBjHxGvRVWGsVQ/zHecPnJqslj4HcDGZK7ETczs2779Znband2qnM9dVgyq2G9slLX69nVKb2HBQ51VgVuivFK5oizx/RSIgSmZlSQDaHHL4IHAnbwoGNWO85ERBFxOerLaNhP0EYrSkNABcJOfqiCRfazIXSxUKQd4XOx3H7c=\', \'password\': \'NXn+tGp/+m3dtqV2Em2fqAs21CQIjm0F05JqPWzNjKUiRvvZG/MTcmilW3xymwqUzfCgM8vNMdOgVqffnD4piFrh3araElM6AW8GcyoUBz+hpEBoYY0X+ZBCXLSHTMWMc1UYbZxnMM9BNng9Mpj9kEgnuc9jE76yN6nE0fNPkvs=\', \'validate\': \'\', \'challenge\': \'\', \'seccode\': \'\'}'
Arguments: ()
2022-01-28 14:41:50,852 - INFO requestbase.py [line:33]: 连通接口"https://gateway-stg.jmj1995.com/authority/auth/login",接口data为:"",接口json{'groupId': '3', 'username': 'zaBjHxGvRVWGsVQ/zHecPnJqslj4HcDGZK7ETczs2779Znband2qnM9dVgyq2G9slLX69nVKb2HBQ51VgVuivFK5oizx/RSIgSmZlSQDaHHL4IHAnbwoGNWO85ERBFxOerLaNhP0EYrSkNABcJOfqiCRfazIXSxUKQd4XOx3H7c=', 'password': 'NXn+tGp/+m3dtqV2Em2fqAs21CQIjm0F05JqPWzNjKUiRvvZG/MTcmilW3xymwqUzfCgM8vNMdOgVqffnD4piFrh3araElM6AW8GcyoUBz+hpEBoYY0X+ZBCXLSHTMWMc1UYbZxnMM9BNng9Mpj9kEgnuc9jE76yN6nE0fNPkvs=', 'validate': '', 'challenge': '', 'seccode': ''}
2022-01-28 14:41:50,852 - INFO requestbase.py [line:33]: 连通接口"https://gateway-stg.jmj1995.com/authority/auth/login",接口data为:"",接口json{'groupId': '3', 'username': 'zaBjHxGvRVWGsVQ/zHecPnJqslj4HcDGZK7ETczs2779Znband2qnM9dVgyq2G9slLX69nVKb2HBQ51VgVuivFK5oizx/RSIgSmZlSQDaHHL4IHAnbwoGNWO85ERBFxOerLaNhP0EYrSkNABcJOfqiCRfazIXSxUKQd4XOx3H7c=', 'password': 'NXn+tGp/+m3dtqV2Em2fqAs21CQIjm0F05JqPWzNjKUiRvvZG/MTcmilW3xymwqUzfCgM8vNMdOgVqffnD4piFrh3araElM6AW8GcyoUBz+hpEBoYY0X+ZBCXLSHTMWMc1UYbZxnMM9BNng9Mpj9kEgnuc9jE76yN6nE0fNPkvs=', 'validate': '', 'challenge': '', 'seccode': ''}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "e:\12\TestCase\test_request.py", line 66, in <module>
    pytest.main(["--alluredir", report_path])
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 120, in runtestprotocol
    rep = call_and_report(item, "setup", log)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 311, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 150, in pytest_runtest_setup
    item.session._setupstate.prepare(item)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 449, in prepare
    col.setup()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 1647, in setup
    self._request._fillfixtures()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 568, in _fillfixtures
    item.funcargs[argname] = self.getfixturevalue(argname)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 581, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 601, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 687, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 1072, in execute
    result = hook.pytest_fixture_setup(fixturedef=self, request=request)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 1126, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\fixtures.py", line 925, in call_fixture_func
    fixture_result = next(generator)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 811, in xunit_setup_class_fixture
    _call_with_optional_argument(func, self.obj)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 739, in _call_with_optional_argument
    func(arg)
  File "E:\12\TestCase\test_request.py", line 36, in setup_class
    requestdata=RequestsHandler().post_Req(url=url,data="",json=json,headers="",params="")
  File ".\Common\requestbase.py", line 38, in post_Req
    self.logger.info(f'等待接口"{url}"时长:{end - start}')
Message: '等待接口"https://gateway-stg.jmj1995.com/authority/auth/login"时长:0:00:00.386380'
Arguments: ()
2022-01-28 14:41:51,245 - INFO requestbase.py [line:38]: 等待接口"https://gateway-stg.jmj1995.com/authority/auth/login"时长:0:00:00.386380
2022-01-28 14:41:51,245 - INFO requestbase.py [line:38]: 等待接口"https://gateway-stg.jmj1995.com/authority/auth/login"时长:0:00:00.386380
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "e:\12\TestCase\test_request.py", line 66, in <module>
    pytest.main(["--alluredir", report_path])
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 311, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 162, in pytest_runtest_call
    item.runtest()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "E:\12\TestCase\test_request.py", line 49, in test_001
    a=Test_request().setup_class()
  File "E:\12\TestCase\test_request.py", line 36, in setup_class
    requestdata=RequestsHandler().post_Req(url=url,data="",json=json,headers="",params="")
  File ".\Common\requestbase.py", line 33, in post_Req
    self.logger.info(f'连通接口"{url}",接口data为:"{data}",接口json{json}')
Message: '连通接口"https://gateway-stg.jmj1995.com/authority/auth/login",接口data为:"",接口json{\'groupId\': \'3\', \'username\': \'zaBjHxGvRVWGsVQ/zHecPnJqslj4HcDGZK7ETczs2779Znband2qnM9dVgyq2G9slLX69nVKb2HBQ51VgVuivFK5oizx/RSIgSmZlSQDaHHL4IHAnbwoGNWO85ERBFxOerLaNhP0EYrSkNABcJOfqiCRfazIXSxUKQd4XOx3H7c=\', \'password\': \'NXn+tGp/+m3dtqV2Em2fqAs21CQIjm0F05JqPWzNjKUiRvvZG/MTcmilW3xymwqUzfCgM8vNMdOgVqffnD4piFrh3araElM6AW8GcyoUBz+hpEBoYY0X+ZBCXLSHTMWMc1UYbZxnMM9BNng9Mpj9kEgnuc9jE76yN6nE0fNPkvs=\', \'validate\': \'\', \'challenge\': \'\', \'seccode\': \'\'}'
Arguments: ()
2022-01-28 14:41:51,250 - INFO requestbase.py [line:33]: 连通接口"https://gateway-stg.jmj1995.com/authority/auth/login",接口data为:"",接口json{'groupId': '3', 'username': 'zaBjHxGvRVWGsVQ/zHecPnJqslj4HcDGZK7ETczs2779Znband2qnM9dVgyq2G9slLX69nVKb2HBQ51VgVuivFK5oizx/RSIgSmZlSQDaHHL4IHAnbwoGNWO85ERBFxOerLaNhP0EYrSkNABcJOfqiCRfazIXSxUKQd4XOx3H7c=', 'password': 'NXn+tGp/+m3dtqV2Em2fqAs21CQIjm0F05JqPWzNjKUiRvvZG/MTcmilW3xymwqUzfCgM8vNMdOgVqffnD4piFrh3araElM6AW8GcyoUBz+hpEBoYY0X+ZBCXLSHTMWMc1UYbZxnMM9BNng9Mpj9kEgnuc9jE76yN6nE0fNPkvs=', 'validate': '', 'challenge': '', 'seccode': ''}
2022-01-28 14:41:51,250 - INFO requestbase.py [line:33]: 连通接口"https://gateway-stg.jmj1995.com/authority/auth/login",接口data为:"",接口json{'groupId': '3', 'username': 'zaBjHxGvRVWGsVQ/zHecPnJqslj4HcDGZK7ETczs2779Znband2qnM9dVgyq2G9slLX69nVKb2HBQ51VgVuivFK5oizx/RSIgSmZlSQDaHHL4IHAnbwoGNWO85ERBFxOerLaNhP0EYrSkNABcJOfqiCRfazIXSxUKQd4XOx3H7c=', 'password': 'NXn+tGp/+m3dtqV2Em2fqAs21CQIjm0F05JqPWzNjKUiRvvZG/MTcmilW3xymwqUzfCgM8vNMdOgVqffnD4piFrh3araElM6AW8GcyoUBz+hpEBoYY0X+ZBCXLSHTMWMc1UYbZxnMM9BNng9Mpj9kEgnuc9jE76yN6nE0fNPkvs=', 'validate': '', 'challenge': '', 'seccode': ''}
2022-01-28 14:41:51,250 - INFO requestbase.py [line:33]: 连通接口"https://gateway-stg.jmj1995.com/authority/auth/login",接口data为:"",接口json{'groupId': '3', 'username': 'zaBjHxGvRVWGsVQ/zHecPnJqslj4HcDGZK7ETczs2779Znband2qnM9dVgyq2G9slLX69nVKb2HBQ51VgVuivFK5oizx/RSIgSmZlSQDaHHL4IHAnbwoGNWO85ERBFxOerLaNhP0EYrSkNABcJOfqiCRfazIXSxUKQd4XOx3H7c=', 'password': 'NXn+tGp/+m3dtqV2Em2fqAs21CQIjm0F05JqPWzNjKUiRvvZG/MTcmilW3xymwqUzfCgM8vNMdOgVqffnD4piFrh3araElM6AW8GcyoUBz+hpEBoYY0X+ZBCXLSHTMWMc1UYbZxnMM9BNng9Mpj9kEgnuc9jE76yN6nE0fNPkvs=', 'validate': '', 'challenge': '', 'seccode': ''}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "e:\12\TestCase\test_request.py", line 66, in <module>
    pytest.main(["--alluredir", report_path])
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 311, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 162, in pytest_runtest_call
    item.runtest()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "E:\12\TestCase\test_request.py", line 49, in test_001
    a=Test_request().setup_class()
  File "E:\12\TestCase\test_request.py", line 36, in setup_class
    requestdata=RequestsHandler().post_Req(url=url,data="",json=json,headers="",params="")
  File ".\Common\requestbase.py", line 38, in post_Req
    self.logger.info(f'等待接口"{url}"时长:{end - start}')
Message: '等待接口"https://gateway-stg.jmj1995.com/authority/auth/login"时长:0:00:00.246373'
Arguments: ()
2022-01-28 14:41:51,497 - INFO requestbase.py [line:38]: 等待接口"https://gateway-stg.jmj1995.com/authority/auth/login"时长:0:00:00.246373
2022-01-28 14:41:51,497 - INFO requestbase.py [line:38]: 等待接口"https://gateway-stg.jmj1995.com/authority/auth/login"时长:0:00:00.246373
2022-01-28 14:41:51,497 - INFO requestbase.py [line:38]: 等待接口"https://gateway-stg.jmj1995.com/authority/auth/login"时长:0:00:00.246373
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "e:\12\TestCase\test_request.py", line 66, in <module>
    pytest.main(["--alluredir", report_path])
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 311, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 162, in pytest_runtest_call
    item.runtest()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "E:\12\TestCase\test_request.py", line 50, in test_001
    requestdata=RequestsHandler().get_Req(url=final_data[0]['url'],params=eval(final_data[0]['params']),headers=a,json="",data="")
  File ".\Common\requestbase.py", line 21, in get_Req
    self.logger.info(f'连通接口"{url}",接口header为:"{headers}",接口param为：{params}')
Message: '连通接口"https://supplychain-server-stg.jmj1995.com/items",接口header为:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxZTkwNDMyN2NiNTg0OWIwODc5Yjg3OTQxZjM1YTNkNSIsImF1dGgiOiIiLCJpZCI6NTk2LCJzdWIiOiIxMiJ9.ShbkjOOHFvZjI8epb-qmRpRoTphZ3f1OGe9jl2NAU6XXEWjE2o-P_v0d6IxxRDyQIX0dKyt-pKBsLB1oOD3AlQ",接口param为：{\'pageNum\': \'1\', \'pageSize\': \'20\'}'
Arguments: ()
2022-01-28 14:41:51,500 - INFO requestbase.py [line:21]: 连通接口"https://supplychain-server-stg.jmj1995.com/items",接口header为:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxZTkwNDMyN2NiNTg0OWIwODc5Yjg3OTQxZjM1YTNkNSIsImF1dGgiOiIiLCJpZCI6NTk2LCJzdWIiOiIxMiJ9.ShbkjOOHFvZjI8epb-qmRpRoTphZ3f1OGe9jl2NAU6XXEWjE2o-P_v0d6IxxRDyQIX0dKyt-pKBsLB1oOD3AlQ",接口param为：{'pageNum': '1', 'pageSize': '20'}
2022-01-28 14:41:51,500 - INFO requestbase.py [line:21]: 连通接口"https://supplychain-server-stg.jmj1995.com/items",接口header为:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxZTkwNDMyN2NiNTg0OWIwODc5Yjg3OTQxZjM1YTNkNSIsImF1dGgiOiIiLCJpZCI6NTk2LCJzdWIiOiIxMiJ9.ShbkjOOHFvZjI8epb-qmRpRoTphZ3f1OGe9jl2NAU6XXEWjE2o-P_v0d6IxxRDyQIX0dKyt-pKBsLB1oOD3AlQ",接口param为：{'pageNum': '1', 'pageSize': '20'}
2022-01-28 14:41:51,500 - INFO requestbase.py [line:21]: 连通接口"https://supplychain-server-stg.jmj1995.com/items",接口header为:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxZTkwNDMyN2NiNTg0OWIwODc5Yjg3OTQxZjM1YTNkNSIsImF1dGgiOiIiLCJpZCI6NTk2LCJzdWIiOiIxMiJ9.ShbkjOOHFvZjI8epb-qmRpRoTphZ3f1OGe9jl2NAU6XXEWjE2o-P_v0d6IxxRDyQIX0dKyt-pKBsLB1oOD3AlQ",接口param为：{'pageNum': '1', 'pageSize': '20'}
2022-01-28 14:41:51,500 - INFO requestbase.py [line:21]: 连通接口"https://supplychain-server-stg.jmj1995.com/items",接口header为:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxZTkwNDMyN2NiNTg0OWIwODc5Yjg3OTQxZjM1YTNkNSIsImF1dGgiOiIiLCJpZCI6NTk2LCJzdWIiOiIxMiJ9.ShbkjOOHFvZjI8epb-qmRpRoTphZ3f1OGe9jl2NAU6XXEWjE2o-P_v0d6IxxRDyQIX0dKyt-pKBsLB1oOD3AlQ",接口param为：{'pageNum': '1', 'pageSize': '20'}
--- Logging error ---
Traceback (most recent call last):
  File ".\Common\requestbase.py", line 24, in get_Req
    res=requests.get(url=url,headers=headers,params=params,data=data,json=json)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 449, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "e:\12\TestCase\test_request.py", line 66, in <module>
    pytest.main(["--alluredir", report_path])
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 311, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\runner.py", line 162, in pytest_runtest_call
    item.runtest()
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "E:\12\TestCase\test_request.py", line 50, in test_001
    requestdata=RequestsHandler().get_Req(url=final_data[0]['url'],params=eval(final_data[0]['params']),headers=a,json="",data="")
  File ".\Common\requestbase.py", line 28, in get_Req
    self.logger.exception(f'等待接口"{url}"失败')
Message: '等待接口"https://supplychain-server-stg.jmj1995.com/items"失败'
Arguments: ()
2022-01-28 14:41:51,502 - ERROR requestbase.py [line:28]: 等待接口"https://supplychain-server-stg.jmj1995.com/items"失败
Traceback (most recent call last):
  File ".\Common\requestbase.py", line 24, in get_Req
    res=requests.get(url=url,headers=headers,params=params,data=data,json=json)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 449, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
2022-01-28 14:41:51,502 - ERROR requestbase.py [line:28]: 等待接口"https://supplychain-server-stg.jmj1995.com/items"失败
Traceback (most recent call last):
  File ".\Common\requestbase.py", line 24, in get_Req
    res=requests.get(url=url,headers=headers,params=params,data=data,json=json)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 449, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
2022-01-28 14:41:51,502 - ERROR requestbase.py [line:28]: 等待接口"https://supplychain-server-stg.jmj1995.com/items"失败
Traceback (most recent call last):
  File ".\Common\requestbase.py", line 24, in get_Req
    res=requests.get(url=url,headers=headers,params=params,data=data,json=json)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 449, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
2022-01-28 14:41:51,502 - ERROR requestbase.py [line:28]: 等待接口"https://supplychain-server-stg.jmj1995.com/items"失败
Traceback (most recent call last):
  File ".\Common\requestbase.py", line 24, in get_Req
    res=requests.get(url=url,headers=headers,params=params,data=data,json=json)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 449, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
