2022-01-27 16:58:38,365 - INFO requestbase.py [line:21]: 连通接口"https://supplychain.dev.jmj1995.com/items",接口header为:"{"authorization":"Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJmMWQ0ZjA0MGJlY2U0NTQ1YTdkMGExZDUwYWE5MjM3MyIsImF1dGgiOiIiLCJpZCI6MTM2LCJzdWIiOiJwZW5namllIn0.y1U_gRL0wQ6h_8RTs-mrtaHd0x6LUQDvEXU3jHqDTvE4RtFPsoxuIyg01iwhk3nQhIC3ZoPZAjSs3x77IxSRTQ"}",接口param为：{"pageNum":"1","pageSize":"20"}
2022-01-27 16:58:38,367 - ERROR requestbase.py [line:28]: 等待接口"https://supplychain.dev.jmj1995.com/items"失败
Traceback (most recent call last):
  File "..\Common\requestbase.py", line 24, in get_Req
    res=requests.get(url=url,headers=header,params=param,data=data,json=json)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 449, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
