2022-01-25 16:53:35,330 - INFO requestbase.py [line:21]: 连通接口"https://supplychain.dev.jmj1995.com/items",接口header为:"{'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJhNzg0MjMwYzY1Nzk0OTRiOTNhM2IyODgxZmY1ZjQ5ZSIsImF1dGgiOiIiLCJpZCI6MTM2LCJzdWIiOiJwZW5namllIn0.9HXZJ9wt2tBNGJN_ixb8FCVG7WT5YJG8mR5H-VFnre3rY3yvuq3_cekzw4kxS7CTjksgvGry-ketbGcOhsSxAw'}",接口param为：{'pageNum': '1', 'pageSize': '20'}
2022-01-25 16:53:35,331 - ERROR requestbase.py [line:28]: 等待接口"https://supplychain.dev.jmj1995.com/items"失败
Traceback (most recent call last):
  File ".\Common\requestbase.py", line 24, in get_Req
    res=requests.get(url=url,headers=header,param=param,data=data,json=json)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bonjour\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'param'
